# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bf27338ec2997e372eabf023b9166df01e35010fc5211870dd92ce1c89a59a33b761609dde2a41830148f5869e8281412d4ee8bcd9c044d5183685a860d5c63

test:
  secret_key_base: fceff50bf93be32d5b310b8fda7d15a165ce94e1f30d9e3a26ee82af9031782281680f3013fcc1898e32a8a84ae63229565a6a598e1115ade50d252e3f072ef3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
